keys:
  - &hosts:
    - &thinkpad age15hqvz3dr8qkpxlx5xxf5umaysyrnkkz6rk4rly7l60n70pmwlpkspncdr8
creation_rules:
  - path_regex: nixosConfigs/userSpecific/passwords.ya?ml$
    key_groups:
    - age:
      - *thinkpad
