keys:
  - &users:
    - &boticelli B9A4275CD70155C26CADA7A1C983E65527C2EB07
  - &hosts:
    - &thinkpad age1k4rwzrpmnvuz6r36ugzk2tdf50d2nu7afecucn2dp4w8sx03a3dsz0phw4
creation_rules:
  - path_regex: nixosConfigs/userSpecific/passwords.ya?ml$
    key_groups:
    - pgp:
      - *boticelli
      age:
      - *thinkpad       
